name = "NoExactlyTwoDloComparator"
version = "1.0.0"
defaultTargets = ["Challenge", "Solution"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "5e932f97dd25535344f80f9dd8da3aab83df0fe6"

[[require]]
name = "NoExactlyTwoDlo"
git = "https://github.com/lioristhmus/no-exactly-two-dlo-lean.git"
rev = "bfa29d66e1850cc881ebdf191bd907bac8af1eda"

[[lean_lib]]
name = "Challenge"

[[lean_lib]]
name = "Solution"
